<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<div class="actions">
    <?php  if($block->needsApproval() && $block->isApprover()) :?>

    <a href="#" >
        <span><?php /* @escapeNotVerified */ echo __('Approve') ?></span>
    </a>
    <a href="#" >
        <span><?php /* @escapeNotVerified */ echo __('Reject') ?></span>
    </a>
    <?php endif ?>
</div>
